#!/bin/sh

# ./new_post my_title

base_name="posts/$1"
mkdir -p "$base_name"
touch "$base_name"/title
touch "$base_name"/tags
echo "$(date)" > "$base_name"/date
touch "$base_name"/content
echo '1' > "$base_name"/publish

echo "Created post $base_name"
